allowBuilds:
  live2dmanager: true
  live2dmanager@https://codeload.github.com/madosuki/live2dManager/tar.gz/63a20f834e5cbad9dd159acd7243bd42e48eb650: set this to true or false
  live2dmanager@https://codeload.github.com/madosuki/live2dManager/tar.gz/94918cd45ca1fea08cc030f1e94526a897691512: true
